name: rusanoff-github-io

services:
  frontend:
    build:
      context: ../..
      dockerfile: ./dockerfiles/dev/Dockerfile
    env_file:
      - ../../.env
    ports:
      - "${VITE_DEV_SERVER_PORT:-5173}:${VITE_DEV_SERVER_PORT:-5173}"
    container_name: frontend
    volumes:
      - ../../:/app
      - /app/node_modules
    develop:
      watch:
        - action: rebuild
          path: ../..
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
