version: "2.19.1"
services:
  frontend:
    ports:
      - "${OUTER_PORT_FRONTEND}:${INNER_PORT_FRONTEND}"
    container_name: frontend
    build: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
    environment:
      - CHOKIDAR_USEPOLLING=true
      - OUTER_PORT_FRONTEND=3001
      - INNER_PORT_FRONTEND=3001
    restart: on-failure:1
    command: npm run dev